local L = LibStub("AceLocale-3.0"):NewLocale("FuzzyChannelCondenser", "deDE")

if not L then return end

L["ChannelDelimiter"] = ", "
L["GainedModeratorChannel"] = "%1$s ist jetzt ein Moderator vom Channel: %2$s."
L["GainedModeratorChannels"] = "%1$s ist jetzt ein Moderator von Channels: %2$s."
L["GainedOwnerAndModeratorChannel"] = "%1$s ist jetzt der Besitzer und ein Moderator vom Channel: %2$s."
L["GainedOwnerAndModeratorChannels"] = "%1$s ist jetzt der Besitzer und ein Moderator von Channels: %2$s."
L["GainedOwnerChannel"] = "%1$s ist jetzt der Besitzer des Channels: %2$s."
L["GainedOwnerChannels"] = "%1$s ist jetzt der Besitzer der Channels: %2$s."
L["JoinedChannel"] = "%1$s ist dem Channel beigetreten: %2$s."
L["JoinedChannels"] = "%1$s ist der Channels beigetreten: %2$s."
L["LeftChannel"] = "%1$s ist den Channel verlassen: %2$s."
L["LeftChannels"] = "%1$s ist die Channels verlassen: %2$s."
-- L["LostModeratorChannel"] = ""
-- L["LostModeratorChannels"] = ""
L["YouChangedChannel"] = "Channel gewechselt: %1$s."
L["YouChangedChannels"] = "Channels gewechselt: %1$s."
L["YouGainedModeratorChannel"] = "Jetzt ein Moderator vom Channel: %1$s."
L["YouGainedModeratorChannels"] = "Jetzt ein Moderator von Channels: %1$s."
L["YouGainedOwnerAndModeratorChannel"] = "Jetzt der Besitzer und ein Moderator vom Channel: %1$s."
L["YouGainedOwnerAndModeratorChannels"] = "Jetzt der Besitzer und ein Moderator von Channels: %1$s."
L["YouGainedOwnerChannel"] = "Jetzt der Besitzer des Channels:"
L["YouGainedOwnerChannels"] = "Jetzt der Besitzer der Channels:"
L["YouJoinedChannel"] = "Channel beigetreten: %1$s."
L["YouJoinedChannels"] = "Channels beigetreten: %1$s."
L["YouLeftChannel"] = "Channel verlassen: %1$s."
L["YouLeftChannels"] = "Channels verlassen: %1$s."
-- L["YouLostModeratorChannel"] = ""
-- L["YouLostModeratorChannels"] = ""
